// import { MeasureUnit } from "@/types/items/feedstock";
// import { ObjProduct } from "@/types/items/product";
// import { randomUUID } from "crypto";

// export const mockProducts: ObjProduct[] = [
//   {
//     id: randomUUID(),
//     name: "Pan Francés",
//     description: "Pan clásico de harina y levadura",
//     product_feedstock: randomUUID(),
//     measure_unit: MeasureUnit.UNIT,
//     quantity: 50,
//     subtotal: 5000,
//     indirect_cost: 800,
//     resale_percentage: 30,
//     public_percentage: 50,
//     created_at: new Date("2025-07-01"),
//     updated_at: new Date("2025-07-01"),
//     is_deleted: false,
//   },
//   {
//     id: randomUUID(),
//     name: "Bizcochuelo Vainilla",
//     description: "Bizcochuelo esponjoso sabor vainilla",
//     product_feedstock: randomUUID(),
//     measure_unit: MeasureUnit.UNIT,
//     quantity: 20,
//     subtotal: 4200,
//     indirect_cost: 600,
//     resale_percentage: 35,
//     public_percentage: 55,
//     created_at: new Date("2025-07-02"),
//     updated_at: new Date("2025-07-02"),
//     is_deleted: false,
//   },
//   {
//     id: randomUUID(),
//     name: "Tarta de Manzana",
//     description: "Tarta dulce con relleno de manzana",
//     product_feedstock: randomUUID(),
//     measure_unit: MeasureUnit.UNIT,
//     quantity: 15,
//     subtotal: 3750,
//     indirect_cost: 500,
//     resale_percentage: 25,
//     public_percentage: 45,
//     created_at: new Date("2025-07-03"),
//     updated_at: new Date("2025-07-03"),
//     is_deleted: false,
//   },
//   {
//     id: randomUUID(),
//     name: "Galletas de Chocolate",
//     description: "Galletas dulces con chips de chocolate",
//     product_feedstock: randomUUID(),
//     measure_unit: MeasureUnit.UNIT,
//     quantity: 100,
//     subtotal: 6000,
//     indirect_cost: 900,
//     resale_percentage: 40,
//     public_percentage: 60,
//     created_at: new Date("2025-07-04"),
//     updated_at: new Date("2025-07-04"),
//     is_deleted: false,
//   },
//   {
//     id: randomUUID(),
//     name: "Budín de Limón",
//     description: "Budín esponjoso sabor limón",
//     product_feedstock: randomUUID(),
//     measure_unit: MeasureUnit.UNIT,
//     quantity: 25,
//     subtotal: 3500,
//     indirect_cost: 550,
//     resale_percentage: 32,
//     public_percentage: 52,
//     created_at: new Date("2025-07-05"),
//     updated_at: new Date("2025-07-05"),
//     is_deleted: false,
//   },
//   {
//     id: randomUUID(),
//     name: "Alfajores de Maicena",
//     description: "Alfajores rellenos con dulce de leche",
//     product_feedstock: randomUUID(),
//     measure_unit: MeasureUnit.UNIT,
//     quantity: 60,
//     subtotal: 4800,
//     indirect_cost: 700,
//     resale_percentage: 28,
//     public_percentage: 48,
//     created_at: new Date("2025-07-06"),
//     updated_at: new Date("2025-07-06"),
//     is_deleted: false,
//   },
//   {
//     id: randomUUID(),
//     name: "Croissant",
//     description: "Medialuna de manteca estilo francés",
//     product_feedstock: randomUUID(),
//     measure_unit: MeasureUnit.UNIT,
//     quantity: 40,
//     subtotal: 5200,
//     indirect_cost: 750,
//     resale_percentage: 33,
//     public_percentage: 53,
//     created_at: new Date("2025-07-07"),
//     updated_at: new Date("2025-07-07"),
//     is_deleted: false,
//   },
//   {
//     id: randomUUID(),
//     name: "Pizza Margarita",
//     description: "Pizza clásica con tomate, mozzarella y albahaca",
//     product_feedstock: randomUUID(),
//     measure_unit: MeasureUnit.UNIT,
//     quantity: 12,
//     subtotal: 7200,
//     indirect_cost: 1000,
//     resale_percentage: 45,
//     public_percentage: 65,
//     created_at: new Date("2025-07-08"),
//     updated_at: new Date("2025-07-08"),
//     is_deleted: false,
//   },
//   {
//     id: randomUUID(),
//     name: "Empanadas de Carne",
//     description: "Empanadas criollas fritas",
//     product_feedstock: randomUUID(),
//     measure_unit: MeasureUnit.UNIT,
//     quantity: 80,
//     subtotal: 6400,
//     indirect_cost: 850,
//     resale_percentage: 30,
//     public_percentage: 50,
//     created_at: new Date("2025-07-09"),
//     updated_at: new Date("2025-07-09"),
//     is_deleted: false,
//   },
//   {
//     id: randomUUID(),
//     name: "Sándwich de Miga",
//     description: "Sándwich de jamón y queso sin corteza",
//     product_feedstock: randomUUID(),
//     measure_unit: MeasureUnit.UNIT,
//     quantity: 50,
//     subtotal: 5000,
//     indirect_cost: 800,
//     resale_percentage: 27,
//     public_percentage: 47,
//     created_at: new Date("2025-07-10"),
//     updated_at: new Date("2025-07-10"),
//     is_deleted: false,
//   },
//   {
//     id: randomUUID(),
//     name: "Torta de Chocolate",
//     description: "Torta húmeda con ganache",
//     product_feedstock: randomUUID(),
//     measure_unit: MeasureUnit.UNIT,
//     quantity: 10,
//     subtotal: 8000,
//     indirect_cost: 1200,
//     resale_percentage: 50,
//     public_percentage: 70,
//     created_at: new Date("2025-07-11"),
//     updated_at: new Date("2025-07-11"),
//     is_deleted: false,
//   },
//   {
//     id: randomUUID(),
//     name: "Medialunas de Grasa",
//     description: "Medialunas tradicionales argentinas",
//     product_feedstock: randomUUID(),
//     measure_unit: MeasureUnit.UNIT,
//     quantity: 35,
//     subtotal: 3500,
//     indirect_cost: 500,
//     resale_percentage: 25,
//     public_percentage: 45,
//     created_at: new Date("2025-07-12"),
//     updated_at: new Date("2025-07-12"),
//     is_deleted: false,
//   },
//   {
//     id: randomUUID(),
//     name: "Focaccia",
//     description: "Pan italiano con aceite de oliva y hierbas",
//     product_feedstock: randomUUID(),
//     measure_unit: MeasureUnit.UNIT,
//     quantity: 15,
//     subtotal: 4500,
//     indirect_cost: 700,
//     resale_percentage: 28,
//     public_percentage: 48,
//     created_at: new Date("2025-07-13"),
//     updated_at: new Date("2025-07-13"),
//     is_deleted: false,
//   },
//   {
//     id: randomUUID(),
//     name: "Brownie",
//     description: "Brownie húmedo con nueces",
//     product_feedstock: randomUUID(),
//     measure_unit: MeasureUnit.UNIT,
//     quantity: 20,
//     subtotal: 3800,
//     indirect_cost: 600,
//     resale_percentage: 32,
//     public_percentage: 52,
//     created_at: new Date("2025-07-14"),
//     updated_at: new Date("2025-07-14"),
//     is_deleted: false,
//   },
//   {
//     id: randomUUID(),
//     name: "Chipa",
//     description: "Panecillo de almidón de mandioca y queso",
//     product_feedstock: randomUUID(),
//     measure_unit: MeasureUnit.UNIT,
//     quantity: 25,
//     subtotal: 3000,
//     indirect_cost: 450,
//     resale_percentage: 20,
//     public_percentage: 40,
//     created_at: new Date("2025-07-15"),
//     updated_at: new Date("2025-07-15"),
//     is_deleted: false,
//   }
// ];
