import os
from dotenv import load_dotenv

load_dotenv()

COOKIE_NAME = os.getenv("COOKIE_NAME")
ACCESS_SECRET_KEY = os.getenv("ACCESS_SECRET_KEY")
REFRESH_SECRET_KEY = os.getenv("REFRESH_SECRET_KEY")
DATABASE_URL = os.getenv("DATABASE_URL")
ALGORITHM = "HS256"
ENCRYPT_KEY = os.getenv('ENCRYPT_KEY')
ACCESS_TOKEN_EXPIRE_MINUTES = int(os.getenv("ACCESS_TOKEN_EXPIRE_MINUTES", 30))
REFRESH_TOKEN_EXPIRE_MINUTES = int(os.getenv("REFRESH_TOKEN_EXPIRE_MINUTES", 120)) 
FRONTEND_URL = os.getenv("FRONTEND_URL")
SENDGRID_API_KEY = os.getenv('SG_API_KEY')
SENDGRID_SENDER = os.getenv('SG_SENDER')