import { ObjFeedstock, MeasureUnit, Currency } from "@/types/items/feedstock";
import { randomUUID } from "crypto";

export const mockFeedstocks: ObjFeedstock[] = [
  {
    id: randomUUID(),
    name: "Harina de trigo 000",
    // sku: "HAR-0001",
    currency: Currency.ARS,
    measure_unit: MeasureUnit.KILOGRAMS,
    unit_cost: 1200,
    provider: "Molinos Río de la Plata",
    entry_date: new Date("2025-08-01"),
    created_at: new Date("2025-08-01"),
    updated_at: new Date("2025-08-01"),
    quantity: 666,
    is_deleted: false,
  },
  {
    id: randomUUID(),
    name: "Azúcar refinada",
    // sku: "AZU-0002",
    currency: Currency.ARS,
    measure_unit: MeasureUnit.KILOGRAMS,
    unit_cost: 950,
    provider: "Ledesma",
    entry_date: new Date("2025-07-28"),
    created_at: new Date("2025-07-28"),
    updated_at: new Date("2025-07-28"),
    quantity: 666,
    is_deleted: false,
  },
  {
    id: randomUUID(),
    name: "Aceite de girasol",
    // sku: "ACE-0003",
    currency: Currency.ARS,
    measure_unit: MeasureUnit.LITERS,
    unit_cost: 2100,
    provider: "Aceitera General Deheza",
    entry_date: new Date("2025-07-30"),
    created_at: new Date("2025-07-30"),
    updated_at: new Date("2025-07-30"),
    quantity: 666,
    is_deleted: false,
  },
  {
    id: randomUUID(),
    name: "Leche entera en polvo",
    // sku: "LEC-0004",
    currency: Currency.USD,
    measure_unit: MeasureUnit.KILOGRAMS,
    unit_cost: 8.5,
    provider: "La Serenísima",
    entry_date: new Date("2025-07-25"),
    created_at: new Date("2025-07-25"),
    updated_at: new Date("2025-07-25"),
    quantity: 666,
    is_deleted: false,
  },
  {
    id: randomUUID(),
    name: "Cacao en polvo",
    // sku: "CAC-0005",
    currency: Currency.USD,
    measure_unit: MeasureUnit.KILOGRAMS,
    unit_cost: 12.3,
    provider: "Nestlé",
    entry_date: new Date("2025-07-20"),
    created_at: new Date("2025-07-20"),
    updated_at: new Date("2025-07-20"),
    quantity: 666,
    is_deleted: false,
  },
  {
    id: randomUUID(),
    name: "Sal fina",
    // sku: "SAL-0006",
    currency: Currency.ARS,
    measure_unit: MeasureUnit.KILOGRAMS,
    unit_cost: 450,
    provider: "Celusal",
    entry_date: new Date("2025-07-22"),
    created_at: new Date("2025-07-22"),
    updated_at: new Date("2025-07-22"),
    quantity: 666,
    is_deleted: false,
  },
  {
    id: randomUUID(),
    name: "Esencia de vainilla",
    // sku: "ESV-0007",
    currency: Currency.ARS,
    measure_unit: MeasureUnit.MILLILITERS,
    unit_cost: 320,
    provider: "Dr. Oetker",
    entry_date: new Date("2025-07-18"),
    created_at: new Date("2025-07-18"),
    updated_at: new Date("2025-07-18"),
    quantity: 666,
    is_deleted: false,
  },
  {
    id: randomUUID(),
    name: "Huevos",
    // sku: "HUE-0008",
    currency: Currency.ARS,
    measure_unit: MeasureUnit.UNIT,
    unit_cost: 120,
    provider: "Granja Los Pinos",
    entry_date: new Date("2025-07-21"),
    created_at: new Date("2025-07-21"),
    updated_at: new Date("2025-07-21"),
    quantity: 666,
    is_deleted: false,
  },
  {
    id: randomUUID(),
    name: "Manteca",
    // sku: "MAN-0009",
    currency: Currency.ARS,
    measure_unit: MeasureUnit.KILOGRAMS,
    unit_cost: 2700,
    provider: "La Serenísima",
    entry_date: new Date("2025-07-19"),
    created_at: new Date("2025-07-19"),
    updated_at: new Date("2025-07-19"),
    quantity: 666,
    is_deleted: false,
  },
  {
    id: randomUUID(),
    name: "Levadura seca",
    // sku: "LEV-0010",
    currency: Currency.USD,
    measure_unit: MeasureUnit.GRAMS,
    unit_cost: 0.5,
    provider: "Levex",
    entry_date: new Date("2025-07-15"),
    created_at: new Date("2025-07-15"),
    updated_at: new Date("2025-07-15"),
    quantity: 666,
    is_deleted: false,
  },
  {
    id: randomUUID(),
    name: "Chocolate cobertura",
    // sku: "CHO-0011",
    currency: Currency.USD,
    measure_unit: MeasureUnit.KILOGRAMS,
    unit_cost: 14.8,
    provider: "Barry Callebaut",
    entry_date: new Date("2025-07-12"),
    created_at: new Date("2025-07-12"),
    updated_at: new Date("2025-07-12"),
    quantity: 666,
    is_deleted: false,
  },
  {
    id: randomUUID(),
    name: "Mermelada de frutilla",
    // sku: "MER-0012",
    currency: Currency.ARS,
    measure_unit: MeasureUnit.KILOGRAMS,
    unit_cost: 1800,
    provider: "Arcor",
    entry_date: new Date("2025-07-10"),
    created_at: new Date("2025-07-10"),
    updated_at: new Date("2025-07-10"),
    quantity: 666,
    is_deleted: false,
  },
  {
    id: randomUUID(),
    name: "Nueces peladas",
    // sku: "NUE-0013",
    currency: Currency.USD,
    measure_unit: MeasureUnit.KILOGRAMS,
    unit_cost: 9.4,
    provider: "Frutos Secos del Valle",
    entry_date: new Date("2025-07-08"),
    created_at: new Date("2025-07-08"),
    updated_at: new Date("2025-07-08"),
    quantity: 666,
    is_deleted: false,
  },
  {
    id: randomUUID(),
    name: "Crema de leche",
    // sku: "CRE-0014",
    currency: Currency.ARS,
    measure_unit: MeasureUnit.LITERS,
    unit_cost: 2500,
    provider: "La Serenísima",
    entry_date: new Date("2025-07-05"),
    created_at: new Date("2025-07-05"),
    updated_at: new Date("2025-07-05"),
    quantity: 666,
    is_deleted: false,
  },
  {
    id: randomUUID(),
    name: "Papel manteca",
    // sku: "PAP-0015",
    currency: Currency.ARS,
    measure_unit: MeasureUnit.OTHERS,
    unit_cost: 900,
    provider: "Cocina Pro",
    entry_date: new Date("2025-07-02"),
    created_at: new Date("2025-07-02"),
    updated_at: new Date("2025-07-02"),
    quantity: 666,
    is_deleted: false,
  }
];
