import { ObjFeedstock } from "@/types/items/feedstock";
import { MeasureUnit, StateMatter } from "@/types/measure/measure-unit";
import { Currency } from "@/types/measure/currency";
import { randomUUID } from "crypto";

export const mockFeedstocks: ObjFeedstock[] = [
  {
    id: randomUUID(),
    name: "Harina de trigo 000",
    sku: "HAR-0001",
    currency: Currency.ARS,
    state: StateMatter.SOLID,
    measure_unit: MeasureUnit.KILOGRAMS,
    unit_cost: 1200,
    provider: "Molinos Río de la Plata",
    date: new Date("2025-08-01"),
    is_deleted: false,
  },
  {
    id: randomUUID(),
    name: "Azúcar refinada",
    sku: "AZU-0002",
    currency: Currency.ARS,
    state: StateMatter.SOLID,
    measure_unit: MeasureUnit.KILOGRAMS,
    unit_cost: 950,
    provider: "Ledesma",
    date: new Date("2025-07-28"),
    is_deleted: false,
  },
  {
    id: randomUUID(),
    name: "Aceite de girasol",
    sku: "ACE-0003",
    currency: Currency.ARS,
    state: StateMatter.LIQUID,
    measure_unit: MeasureUnit.LITERS,
    unit_cost: 2100,
    provider: "Aceitera General Deheza",
    date: new Date("2025-07-30"),
    is_deleted: false,
  },
  {
    id: randomUUID(),
    name: "Leche entera en polvo",
    sku: "LEC-0004",
    currency: Currency.USD,
    state: StateMatter.SOLID,
    measure_unit: MeasureUnit.KILOGRAMS,
    unit_cost: 8.5,
    provider: "La Serenísima",
    date: new Date("2025-07-25"),
    is_deleted: false,
  },
  {
    id: randomUUID(),
    name: "Cacao en polvo",
    sku: "CAC-0005",
    currency: Currency.USD,
    state: StateMatter.SOLID,
    measure_unit: MeasureUnit.GRAMS,
    unit_cost: 12.3,
    provider: "Nestlé",
    date: new Date("2025-07-20"),
    is_deleted: false,
  },
  {
    id: randomUUID(),
    name: "Sal fina",
    sku: "SAL-0006",
    currency: Currency.ARS,
    state: StateMatter.SOLID,
    measure_unit: MeasureUnit.KILOGRAMS,
    unit_cost: 450,
    provider: "Celusal",
    date: new Date("2025-07-22"),
    is_deleted: false,
  },
  {
    id: randomUUID(),
    name: "Esencia de vainilla",
    sku: "ESV-0007",
    currency: Currency.ARS,
    state: StateMatter.LIQUID,
    measure_unit: MeasureUnit.MILLILITERS,
    unit_cost: 320,
    provider: "Dr. Oetker",
    date: new Date("2025-07-18"),
    is_deleted: false,
  },
  {
    id: randomUUID(),
    name: "Huevos",
    sku: "HUE-0008",
    currency: Currency.ARS,
    state: StateMatter.SOLID,
    measure_unit: MeasureUnit.UNITS,
    unit_cost: 120,
    provider: "Granja Los Pinos",
    date: new Date("2025-07-21"),
    is_deleted: false,
  },
  {
    id: randomUUID(),
    name: "Manteca",
    sku: "MAN-0009",
    currency: Currency.ARS,
    state: StateMatter.SOLID,
    measure_unit: MeasureUnit.GRAMS,
    unit_cost: 2700,
    provider: "La Serenísima",
    date: new Date("2025-07-19"),
    is_deleted: false,
  },
  {
    id: randomUUID(),
    name: "Levadura seca",
    sku: "LEV-0010",
    currency: Currency.USD,
    state: StateMatter.SOLID,
    measure_unit: MeasureUnit.GRAMS,
    unit_cost: 0.5,
    provider: "Levex",
    date: new Date("2025-07-15"),
    is_deleted: false,
  },
  {
    id: randomUUID(),
    name: "Chocolate cobertura",
    sku: "CHO-0011",
    currency: Currency.USD,
    state: StateMatter.SOLID,
    measure_unit: MeasureUnit.KILOGRAMS,
    unit_cost: 14.8,
    provider: "Barry Callebaut",
    date: new Date("2025-07-12"),
    is_deleted: false,
  },
  {
    id: randomUUID(),
    name: "Mermelada de frutilla",
    sku: "MER-0012",
    currency: Currency.ARS,
    state: StateMatter.SOLID,
    measure_unit: MeasureUnit.GRAMS,
    unit_cost: 1800,
    provider: "Arcor",
    date: new Date("2025-07-10"),
    is_deleted: false,
  },
  {
    id: randomUUID(),
    name: "Nueces peladas",
    sku: "NUE-0013",
    currency: Currency.USD,
    state: StateMatter.SOLID,
    measure_unit: MeasureUnit.GRAMS,
    unit_cost: 9.4,
    provider: "Frutos Secos del Valle",
    date: new Date("2025-07-08"),
    is_deleted: false,
  },
  {
    id: randomUUID(),
    name: "Crema de leche",
    sku: "CRE-0014",
    currency: Currency.ARS,
    state: StateMatter.LIQUID,
    measure_unit: MeasureUnit.MILLILITERS,
    unit_cost: 2500,
    provider: "La Serenísima",
    date: new Date("2025-07-05"),
    is_deleted: false,
  },
  {
    id: randomUUID(),
    name: "Papel manteca",
    sku: "PAP-0015",
    currency: Currency.ARS,
    state: StateMatter.SOLID,
    measure_unit: MeasureUnit.METERS,
    unit_cost: 900,
    provider: "Cocina Pro",
    date: new Date("2025-07-02"),
    is_deleted: false,
  },
  {
    id: randomUUID(),
    name: "Queso mozzarella",
    sku: "QUE-0016",
    currency: Currency.ARS,
    state: StateMatter.SOLID,
    measure_unit: MeasureUnit.KILOGRAMS,
    unit_cost: 3500,
    provider: "La Paulina",
    date: new Date("2025-07-01"),
    is_deleted: false,
  },
  {
    id: randomUUID(),
    name: "Tomate triturado",
    sku: "TOM-0017",
    currency: Currency.ARS,
    state: StateMatter.LIQUID,
    measure_unit: MeasureUnit.LITERS,
    unit_cost: 1200,
    provider: "La Campagnola",
    date: new Date("2025-06-28"),
    is_deleted: false,
  },
  {
    id: randomUUID(),
    name: "Jamón cocido",
    sku: "JAM-0018",
    currency: Currency.ARS,
    state: StateMatter.SOLID,
    measure_unit: MeasureUnit.KILOGRAMS,
    unit_cost: 4200,
    provider: "Paladini",
    date: new Date("2025-06-25"),
    is_deleted: false,
  }
];
