import type { Metadata } from "next";
import { Geist_Mono, Nunito } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import Header from "@/layouts/header";
import Footer from "@/layouts/footer";
import ReactQueryProvider from "@/providers/query-client-provider";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cotzia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${nunito.variable} ${nunito.className} ${geistMono.variable} antialiased flex flex-col justify-between h-svh max-w-svw`}
      >
        <ReactQueryProvider>
          <Header />
          {children}
          <Toaster />
          <Footer />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
